(WIP) Initial changes to implement the `stack` data location
matter-labs/solidity pull request #3
Opened 2023-02-01 12:43 UTC by abinavpp

2023-02-01 15:53 UTC, hedgar2017 requested changes

2023-02-01 15:53 UTC, hedgar2017 commented on libsolidity/codegen/YulUtilFunctions.cpp
> +			("alloc", _type.location() == DataLocation::Stack ? stackAllocationFunction() : allocationFunction())
The latter worth renaming into `heapAllocationFunction`

2023-02-01 15:53 UTC, hedgar2017 commented on libsolidity/codegen/YulUtilFunctions.h
> +	/// @returns a function that reads a value type from stack address. Performs
We won't have stack addresses in Yul, only variables.
The stack is allocated and managed by LLVM.

2023-02-01 15:53 UTC, hedgar2017 commented on libsolidity/codegen/YulUtilFunctions.h
> +	/// signature: (size) -> memPtr
We won't have stack addresses in Yul, only variables.
The stack is allocated and managed by LLVM.

2023-02-01 15:53 UTC, hedgar2017 commented on libyul/backends/evm/EVMDialect.cpp
> +	reserved.emplace("allocstk");
We won't have stack addresses in Yul, only variables.
The stack is allocated and managed by LLVM.
(in case I understood this piece correctly)

2023-02-01 15:53 UTC, hedgar2017 commented on libyul/backends/evm/EVMDialect.cpp
> +	builtins.emplace(createVerbatimWrapper("allocstk", 1, 1, true));
The same here.

2023-02-02 08:48 UTC, abinavpp commented
I was thinking if we can lower `allocstk(sz)` to `%alloca.ptr = alloca [<sz> x i8]` and lower the access (i.e. `stkload` and `sktstore`) as `gep = getelementptr [<sz> x i8] %alloca.ptr ...` followed by a load/store from `gep`, where the `gep` is translated from the address calculation in yul.

As far as I understand, we should have pointer to stack allocations in yul similar to llvm. Since yul already tracks pointer to heap via the default typed scalar variables, we're doing the same with the stack.

Maybe I'm missing the difficulty in lowering this to llvm as I mentioned. I'm guessing it is difficult to understand what variables are pointers, which add/mul yul expressions must be lowered to getelementptr etc.? If so, are we sure there's no other way to represent array allocation in the stack using pointers like llvm in yul?

2023-02-04 16:54 UTC, closed without merging